name: build and deploy to s3
on:
  push:
    branches:
    - dev

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
        - uses: actions/checkout@v1

        - name: Install dependencies
          run: |
              git clone https://github.com/wkocjan/gatsby-contentful-portfolio.git
              npm install
              npm install -g gatsby-cli

        - name: Build
          run: gatsby build

        - name: Deploy
          uses: lbertenasco/s3-deploy@v1
          with:
            folder: public
            bucket: ${{ secrets.S3_BUCKET }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /*
